version: '3.8'

services: 

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/rfschoombee/containers/volumes/gluetun:/gluetun
    privileged: true 
    ports:
      - 6077:6077
      - 8082:8082
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    environment:
      - VPN_TYPE=openvpn
      - VPN_SERVICE_PROVIDER=privatevpn
      - OPENVPN_USER=${vpn_username}
      - OPENVPN_PASSWORD=${vpn_password}
      - SERVER_COUNTRIES=Netherlands
      - HEALTH_VPN_DURATION_INITIAL=15s
      - FIREWALL_INPUT_PORTS=9999
      - FIREWALL_VPN_INPUT_PORTS=9999
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: container:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/rfschoombee/containers/volumes/sabnzbd/data:/config
      - /d/downloads:/downloads 
      - /d/incomplete/downloads:/incomplete-downloads
    restart: unless-stopped
    depends_on:
      - gluetun

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/rfschoombee/containers/volumes/sonarr/config:/config
      - /d/media/tv:/tv
      - /d/downloads:/downloads
    ports:    
      - 8989:8989
    restart: unless-stopped
    networks:
      - default

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/rfschoombee/containers/volumes/radarr/config:/config
      - /d/media/movies:/movies
      - /d/downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - default

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/rfschoombee/containers/volumes/jellyseerr/config:/app/config
      - /home/rfschoombee/containers/volumes/jellyseerr/downloads:/downloads
    ports:    
      - 5055:5055
    restart: unless-stopped
    networks:
      - default

  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    group_add:
      - "105"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/rfschoombee/containers/volumes/jellyfin/library:/config
      - /d/media/tv:/data/tvshows
      - /d/media/movies:/data/movies
      - /d/media/channels:/data/channels
    ports:    
      - 8096:8096
      - 1900:1900
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3'  

networks:
  default:  
